13-07-19 09:47:21.406 v [main] com.puritytech.crawler.log.TestLogger, line 18  ERROR  :: error
13-07-19 10:41:49.335 v [main] com.puritytech.crawler.log.TestLogger, line 30  ERROR  :: error
13-07-19 10:42:46.205 v [main] com.puritytech.crawler.log.TestLogger, line 30  ERROR  :: error
13-07-19 10:43:38.542 v [main] com.puritytech.crawler.log.TestLogger, line 30  ERROR  :: error
13-07-19 10:44:34.969 v [main] com.puritytech.crawler.log.TestLogger, line 30  ERROR  :: error
13-07-19 10:49:01.730 v [main] com.puritytech.crawler.log.TestLogger, line 33  ERROR  :: error
13-07-19 10:50:45.663 v [main] com.puritytech.crawler.log.TestLogger, line 33  ERROR  :: error
13-07-23 18:53:14.135 v [main] com.puritytech.crawler.xs.XosoMBCrawler, line 348  ERROR  :: Duplicate entry '2013-07-16' for key 'date'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2013-07-16' for key 'date'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
	at com.puritytech.db.Database.executeQuery(Database.java:169)
	at com.puritytech.crawler.xs.XosoMBCrawler.insertXosoSql(XosoMBCrawler.java:345)
	at com.puritytech.crawler.xs.XosoMBCrawler.extract(XosoMBCrawler.java:374)
	at com.puritytech.crawler.xs.XosoMBCrawler.getListItems(XosoMBCrawler.java:499)
	at com.puritytech.crawler.xs.XosoMBCrawler.Processing(XosoMBCrawler.java:520)
	at com.puritytech.crawler.xs.XosoMBCrawler.<init>(XosoMBCrawler.java:124)
	at com.puritytech.crawler.xs.XosoMBCrawler.main(XosoMBCrawler.java:693)
13-07-23 18:53:14.339 v [main] com.puritytech.crawler.xs.XosoMBCrawler, line 348  ERROR  :: Duplicate entry '2013-07-17' for key 'date'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2013-07-17' for key 'date'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
	at com.puritytech.db.Database.executeQuery(Database.java:169)
	at com.puritytech.crawler.xs.XosoMBCrawler.insertXosoSql(XosoMBCrawler.java:345)
	at com.puritytech.crawler.xs.XosoMBCrawler.extract(XosoMBCrawler.java:374)
	at com.puritytech.crawler.xs.XosoMBCrawler.getListItems(XosoMBCrawler.java:499)
	at com.puritytech.crawler.xs.XosoMBCrawler.Processing(XosoMBCrawler.java:520)
	at com.puritytech.crawler.xs.XosoMBCrawler.<init>(XosoMBCrawler.java:124)
	at com.puritytech.crawler.xs.XosoMBCrawler.main(XosoMBCrawler.java:693)
13-07-23 18:53:14.520 v [main] com.puritytech.crawler.xs.XosoMBCrawler, line 348  ERROR  :: Duplicate entry '2013-07-18' for key 'date'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2013-07-18' for key 'date'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
	at com.puritytech.db.Database.executeQuery(Database.java:169)
	at com.puritytech.crawler.xs.XosoMBCrawler.insertXosoSql(XosoMBCrawler.java:345)
	at com.puritytech.crawler.xs.XosoMBCrawler.extract(XosoMBCrawler.java:374)
	at com.puritytech.crawler.xs.XosoMBCrawler.getListItems(XosoMBCrawler.java:499)
	at com.puritytech.crawler.xs.XosoMBCrawler.Processing(XosoMBCrawler.java:520)
	at com.puritytech.crawler.xs.XosoMBCrawler.<init>(XosoMBCrawler.java:124)
	at com.puritytech.crawler.xs.XosoMBCrawler.main(XosoMBCrawler.java:693)
13-07-23 18:53:14.684 v [main] com.puritytech.crawler.xs.XosoMBCrawler, line 348  ERROR  :: Duplicate entry '2013-07-19' for key 'date'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2013-07-19' for key 'date'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
	at com.puritytech.db.Database.executeQuery(Database.java:169)
	at com.puritytech.crawler.xs.XosoMBCrawler.insertXosoSql(XosoMBCrawler.java:345)
	at com.puritytech.crawler.xs.XosoMBCrawler.extract(XosoMBCrawler.java:374)
	at com.puritytech.crawler.xs.XosoMBCrawler.getListItems(XosoMBCrawler.java:499)
	at com.puritytech.crawler.xs.XosoMBCrawler.Processing(XosoMBCrawler.java:520)
	at com.puritytech.crawler.xs.XosoMBCrawler.<init>(XosoMBCrawler.java:124)
	at com.puritytech.crawler.xs.XosoMBCrawler.main(XosoMBCrawler.java:693)
13-07-23 18:53:14.851 v [main] com.puritytech.crawler.xs.XosoMBCrawler, line 348  ERROR  :: Duplicate entry '2013-07-20' for key 'date'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2013-07-20' for key 'date'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
	at com.puritytech.db.Database.executeQuery(Database.java:169)
	at com.puritytech.crawler.xs.XosoMBCrawler.insertXosoSql(XosoMBCrawler.java:345)
	at com.puritytech.crawler.xs.XosoMBCrawler.extract(XosoMBCrawler.java:374)
	at com.puritytech.crawler.xs.XosoMBCrawler.getListItems(XosoMBCrawler.java:499)
	at com.puritytech.crawler.xs.XosoMBCrawler.Processing(XosoMBCrawler.java:520)
	at com.puritytech.crawler.xs.XosoMBCrawler.<init>(XosoMBCrawler.java:124)
	at com.puritytech.crawler.xs.XosoMBCrawler.main(XosoMBCrawler.java:693)
13-07-23 18:53:15.012 v [main] com.puritytech.crawler.xs.XosoMBCrawler, line 348  ERROR  :: Duplicate entry '2013-07-21' for key 'date'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2013-07-21' for key 'date'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
	at com.puritytech.db.Database.executeQuery(Database.java:169)
	at com.puritytech.crawler.xs.XosoMBCrawler.insertXosoSql(XosoMBCrawler.java:345)
	at com.puritytech.crawler.xs.XosoMBCrawler.extract(XosoMBCrawler.java:374)
	at com.puritytech.crawler.xs.XosoMBCrawler.getListItems(XosoMBCrawler.java:499)
	at com.puritytech.crawler.xs.XosoMBCrawler.Processing(XosoMBCrawler.java:520)
	at com.puritytech.crawler.xs.XosoMBCrawler.<init>(XosoMBCrawler.java:124)
	at com.puritytech.crawler.xs.XosoMBCrawler.main(XosoMBCrawler.java:693)
13-07-23 18:53:15.262 v [main] com.puritytech.crawler.xs.XosoMBCrawler, line 348  ERROR  :: Duplicate entry '2013-07-22' for key 'date'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2013-07-22' for key 'date'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
	at com.puritytech.db.Database.executeQuery(Database.java:169)
	at com.puritytech.crawler.xs.XosoMBCrawler.insertXosoSql(XosoMBCrawler.java:345)
	at com.puritytech.crawler.xs.XosoMBCrawler.extract(XosoMBCrawler.java:374)
	at com.puritytech.crawler.xs.XosoMBCrawler.getListItems(XosoMBCrawler.java:499)
	at com.puritytech.crawler.xs.XosoMBCrawler.Processing(XosoMBCrawler.java:520)
	at com.puritytech.crawler.xs.XosoMBCrawler.<init>(XosoMBCrawler.java:124)
	at com.puritytech.crawler.xs.XosoMBCrawler.main(XosoMBCrawler.java:693)
13-07-23 18:53:15.516 v [Timer-0] com.puritytech.crawler.xs.XosoMBCrawler, line 348  ERROR  :: Duplicate entry '2013-07-23' for key 'date'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2013-07-23' for key 'date'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
	at com.puritytech.db.Database.executeQuery(Database.java:169)
	at com.puritytech.crawler.xs.XosoMBCrawler.insertXosoSql(XosoMBCrawler.java:345)
	at com.puritytech.crawler.xs.XosoMBCrawler.extract(XosoMBCrawler.java:374)
	at com.puritytech.crawler.xs.XosoMBCrawler.getListItems(XosoMBCrawler.java:499)
	at com.puritytech.crawler.xs.XosoMBCrawler.Processing(XosoMBCrawler.java:520)
	at com.puritytech.crawler.xs.XosoMBCrawler.run(XosoMBCrawler.java:536)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)
13-08-01 10:08:20.174 v [main] com.puritytech.crawler.xs.XosoMBCrawler, line 391  ERROR  :: error to get ket qua xoso
13-08-01 10:08:20.319 v [main] com.puritytech.crawler.xs.XosoMBCrawler, line 391  ERROR  :: error to get ket qua xoso
13-08-01 10:08:20.455 v [main] com.puritytech.crawler.xs.XosoMBCrawler, line 391  ERROR  :: error to get ket qua xoso
13-08-01 10:16:44.897 v [main] com.puritytech.crawler.xs.XosoMBCrawler, line 354  ERROR  :: Duplicate entry '2013-07-11' for key 'date'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2013-07-11' for key 'date'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
	at com.puritytech.db.Database.executeQuery(Database.java:171)
	at com.puritytech.crawler.xs.XosoMBCrawler.insertXosoSql(XosoMBCrawler.java:351)
	at com.puritytech.crawler.xs.XosoMBCrawler.extract(XosoMBCrawler.java:380)
	at com.puritytech.crawler.xs.XosoMBCrawler.getListItems(XosoMBCrawler.java:505)
	at com.puritytech.crawler.xs.XosoMBCrawler.Processing(XosoMBCrawler.java:526)
	at com.puritytech.crawler.xs.XosoMBCrawler.<init>(XosoMBCrawler.java:127)
	at com.puritytech.crawler.xs.XosoMBCrawler.main(XosoMBCrawler.java:700)
13-08-01 10:16:45.079 v [main] com.puritytech.crawler.xs.XosoMBCrawler, line 354  ERROR  :: Duplicate entry '2013-07-18' for key 'date'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2013-07-18' for key 'date'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
	at com.puritytech.db.Database.executeQuery(Database.java:171)
	at com.puritytech.crawler.xs.XosoMBCrawler.insertXosoSql(XosoMBCrawler.java:351)
	at com.puritytech.crawler.xs.XosoMBCrawler.extract(XosoMBCrawler.java:380)
	at com.puritytech.crawler.xs.XosoMBCrawler.getListItems(XosoMBCrawler.java:505)
	at com.puritytech.crawler.xs.XosoMBCrawler.Processing(XosoMBCrawler.java:526)
	at com.puritytech.crawler.xs.XosoMBCrawler.<init>(XosoMBCrawler.java:127)
	at com.puritytech.crawler.xs.XosoMBCrawler.main(XosoMBCrawler.java:700)
13-08-01 10:39:39.813 v [main] com.puritytech.crawler.xs.XosoMBCrawler, line 510  ERROR  :: xsEle NULL, failed to get data from: http://ketqua.net/xo-so-binh-dinh.php?ngay=22/12/2011
